name: boostsecurity.io - snyk
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  boost-snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Snyk
        uses: boostsecurityio/boostsec-scanner-github@v4
        with:
          api_token: ${{ secrets.BOOST_API_TOKEN }}
          registry_module: boostsecurityio/snyk-test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
